services:
    Haskel\GrpcWebBundle\ArgumentResolver\GrpcRequestValueResolver: ~
    
    Haskel\GrpcWebBundle\ResponseListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView', priority: 0 }
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException', priority: 0 }
